language: go
sudo: false
go:
  - 1.x
before_install:
  - export GO111MODULE=on
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - go test -race ./...
  - go test -c -covermode=count -coverpkg=github.com/hexdigest/bertlv
  - ./bertlv.test -test.coverprofile coverage.cov
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.cov
